/// <reference lib="webworker" />

import { precacheAndRoute } from "workbox-precaching"

declare const self: ServiceWorkerGlobalScope

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
precacheAndRoute(self.__WB_MANIFEST || [])

self.addEventListener("push", (event) => {
  const data = event.data?.json() ?? { title: "Space Ping Pong", body: "A new notification!" }
  event.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body,
      icon: "/icons/icon-192x192.png",
    }),
  )
})

self.addEventListener("sync", (event) => {
  if (event.tag === "sync-data") {
    event.waitUntil(
      // Placeholder for background data synchronization
      console.log("Background sync triggered!"),
    )
  }
})
